### ISSUE TITLE
SOT: L1+TSV

### ISSUE THREAD

**Issue by HajimeKawahara** [HajimeKawahara/jaxsot#1]
Global Mapping of an Exo-Earth using Sparse Modeling
Masataka Aizawa, Hajime Kawahara, Siteng Fan, ApJ 896, 22 (2020) [arXiv:2004.03941](https://arxiv.org/abs/2004.03941),

**Comment by HajimeKawahara** [comment]
l1tsv branch

**Comment by HajimeKawahara** [comment]
@atsuki-kuwata 
@2ndmk2

I tested the L1+TSV in `l1tsv` branch (examples/sotl1tsv.py), but felt something wrong. What do you think about this result:

![L1tsv](https://user-images.githubusercontent.com/15956904/156669386-806caffd-46ce-4928-a28c-eb39d4932b13.png)

Is this a problem of the determination of hyperparameters?

**Comment by 2ndmk2** [comment]
<img width="827" alt="スクリーンショット 2022-03-04 9 57 24" src="https://user-images.githubusercontent.com/23694434/156684458-e8e8b290-2e04-4f84-ad99-6936d95135f1.png">

**Comment by 2ndmk2** [comment]
What is the problem? The figure is flipped horizontally?
I also produce the L2 map, and it looks the same.

**Comment by HajimeKawahara** [comment]
True. :smile: 
![Figure_1](https://user-images.githubusercontent.com/15956904/156685420-dbeeab2e-eae0-496a-b6fe-672eda160920.png)

**Comment by 2ndmk2** [comment]
👍
